overrides:
  ceph:
    log-ignorelist:
    - but it is still running
    - objects unfound and apparently lost
    - \(POOL_APP_NOT_ENABLED\)
tasks:
- thrashosds:
    timeout: 1200
    chance_pgnum_grow: 1
    chance_pgnum_shrink: 1
    chance_pgpnum_fix: 1
